# Generated by Django 5.2.5 on 2026-08-14 16:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_granted', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grant_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cause', models.CharField(choices=[('GRANT', 'Credit grant'), ('BOOKING', 'Booking'), ('REFUND', 'Cancellation refund')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='bookings.booking')),
                ('credit_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credits.creditpack')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='creditpack',
            index=models.Index(fields=['member', 'expiry_date'], name='credit_member_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['member', 'created_at'], name='credit_tx_member_time_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_pack', 'created_at'], name='credit_tx_pack_time_idx'),
        ),
    ]
