# Generated by Django 5.2.5 on 2026-08-19 06:03

import apps.studios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='timezone',
            field=models.CharField(help_text='e.g. Asia/Kolkata', max_length=64, validators=[apps.studios.validators.validate_iana_timezone]),
        ),
    ]
