# Generated by Django 5.2.5 on 2026-08-14 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='classes.fitnessclass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['fitness_class', 'created_at'], name='waitlist_class_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'fitness_class'), name='unique_member_class_waitlist')],
            },
        ),
    ]
